//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::article_tag_rela::Entity as ArticleTagRela;
pub use super::articles::Entity as Articles;
pub use super::leave_messages::Entity as LeaveMessages;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
