version: '3'
services:
  blog_mysql:
    image: mysql:8.0
    container_name: blog_mysql_cn
    restart: on-failure
    ports:
      - "6001:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blogmima
      - MYSQL_ROOT_PASSWORD=blogmima
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  blog_mysql_admin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_mysql_admin_cn
    restart: on-failure
    ports:
      - "6002:80"
    environment:
      - PMA_ARBITRARY=0
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blogmima
      - MYSQL_ROOT_PASSWORD=blogmima
      - PMA_HOST=blog_mysql
    depends_on:
      - blog_mysql
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: blog_meilisearch_cn
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch/data.ms:/data.ms
    environment:
      - MEILI_HTTP_ADMIN_ENABLED=true
      - MEILI_MASTER_KEY=meilisearch_master_key  
  filerun:
      image: filerun/filerun:8.1
      container_name: blog_filerun_cn
      restart: on-failure
      ports:
        - "6004:80"
      volumes:
        - ./filerun/filerun-data:/var/www/html
        - ./filerun/filerun-files:/user-files
      environment:
        - MYSQL_PASSWORD=filerun
        - MYSQL_DATABASE=filerun
        - MYSQL_USER=filerun
        - MYSQL_ROOT_PASSWORD=root
      depends_on:
        - filerun_db

  filerun_db:
    image: mysql:5.7
    container_name: blog_filerun_db_cn
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=filerun
      - MYSQL_USER=filerun
      - MYSQL_PASSWORD=filerun
    volumes:
      - ./filerun/db-data:/var/lib/mysql

