[package]
name = "entity"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
sea-orm = { version = "1.1.1",  features = [ "sqlx-mysql", "runtime-tokio-rustls", "macros" ] }